# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RestTemplate Configuration
resttemplate.connect-timeout=5000
resttemplate.read-timeout=5000

# JWT Configuration
jwt.secret-key=jjlaCTLptvOMSnesdmZbN2U/aL/623kNWTzPk3OHlrk=
jwt.expiration-time=60s

# Dynamic Test
config.message=Halo test update
